### ISSUE TITLE
Нет файла базы данных

### ISSUE THREAD

**Issue by mancj** [rabotyaga/bars-android#1]
А где взять базу данных? При запуске приложения из кода, падает с ошибкой о том, что нужных таблиц нет в бд

**Comment by rabotyaga** [comment]
Могу выслать по почте например. mancjone@gmail.com ?

**Comment by mancj** [comment]
Да, если можно. Спасибо!
9 нояб. 2018 г., 10:36 +0300, rabotyaga <notifications@github.com>, писал:

**Comment by rabotyaga** [comment]
выслал
